#!/usr/bin/env bash
# Web3 orchestrator demo — runs stack detect + static audit on sandbox contract.
# Usage: bash scripts/run-web3-orchestrator-demo.sh [path/to/Contract.sol]
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export PATH="${HOME}/.local/bin:${PATH}"

TARGET="${1:-scripts/sandbox/contracts/RevertOnWithdraw.sol}"
REPORT_DIR="${ROOT}/reports"
ARTIFACT_DIR="${ROOT}/artifacts/web3-audit/demo-run"
mkdir -p "$REPORT_DIR" "$ARTIFACT_DIR"

echo "=== Web3 Orchestrator Demo ==="
echo "Target: $TARGET"
echo

echo "--- 1/4 Smoke (infra) ---"
bash scripts/run-orchestrator-smoke-tests.sh

echo
echo "--- 2/4 Stack detect + static audit ---"
TARGET="${TARGET}" ARTIFACT_DIR="${ARTIFACT_DIR}" REPORT_DIR="${REPORT_DIR}" python3 << 'PY'
import json, os, sys
from pathlib import Path
sys.path.insert(0, "src")
from hexstrike.mcp.web3_audit_runner import detect_web3_audit_stack
from hexstrike.mcp.solidity_audit_runner import (
    parse_contract, slither_run_detectors, check_swc_patterns,
    slither_structure, generate_audit_report_skeleton,
)

target = os.environ["TARGET"]
out = Path(os.environ["ARTIFACT_DIR"])
report_dir = Path(os.environ["REPORT_DIR"])
stack = detect_web3_audit_stack()
parsed = parse_contract(target)
slither = slither_run_detectors(target)
swc = check_swc_patterns(target)
structure = slither_structure(target)
skeleton = generate_audit_report_skeleton(
    parsed.get("contracts", [{}])[0].get("name", "Contract"), purpose="defi"
)

issues = swc.get("issues") or swc.get("swc_matches") or []
bundle = {
    "target": target,
    "stack": stack,
    "parsed": parsed,
    "slither": slither,
    "swc": swc,
    "structure": {"success": structure.get("success"), "call_graph": structure.get("call_graph")},
    "skeleton": skeleton,
    "issue_count": len(issues),
}
out.mkdir(parents=True, exist_ok=True)
(out / "audit_bundle.json").write_text(json.dumps(bundle, indent=2, default=str))

# Markdown report from real MCP output only
lines = [
    "# Audit Report (demo run)",
    "",
    f"**Target:** \`{target}\`",
    f"**Audit ID:** {swc.get('audit_id', 'n/a')}",
    "",
    "## Summary",
    "",
    f"- Contract: **{parsed.get('contracts', [{}])[0].get('name', '?')}**",
    f"- Slither available: **{stack.get('local_tools', {}).get('tools', {}).get('slither', False)}**",
    f"- SWC heuristic issues: **{len(issues)}**",
    f"- Slither findings: **{len(slither.get('findings') or [])}** (success={slither.get('success')})",
    "",
    "## Stack status",
    "",
    "| Tool | Available |",
    "|------|-----------|",
]
tools = (stack.get("local_tools") or {}).get("tools") or {}
for name, ok in sorted(tools.items()):
    lines.append(f"| {name} | {ok} |")

lines += ["", "## Findings", "", "| id | severity | swc_id | source | description |", "|----|----------|--------|--------|-------------|"]
for i, issue in enumerate(issues, 1):
    lines.append(
        f"| F-{i:03d} | {issue.get('severity', issue.get('impact', '?'))} | "
        f"{issue.get('swc_id', '-')} | {issue.get('source', 'swc')} | "
        f"{issue.get('description', issue.get('title', ''))[:80]} |"
    )
if not issues:
    lines.append("| — | — | — | — | No issues from MCP heuristics |")

lines += [
    "",
    "## Skipped / gaps",
    "",
]
api = (stack.get("api_env") or {})
for k, v in sorted(api.items()):
    if not v:
        lines.append(f"- `{k}` — not configured")
if not tools.get("foundry"):
    lines.append("- Foundry MCP — install Foundry for local PoC tests")
if not tools.get("aderyn"):
    lines.append("- Aderyn — not installed")

lines += [
    "",
    "## Artifacts",
    "",
    f"- JSON bundle: \`{out / 'audit_bundle.json'}\`",
    f"- SWC raw: \`{swc.get('raw_report_path', 'n/a')}\`",
    "",
    "_Generated by scripts/run-web3-orchestrator-demo.sh — MCP output only, no fabricated findings._",
]

report_path = report_dir / f"audit-{Path(target).stem}-demo.md"
report_path.write_text("\n".join(lines) + "\n")
print(f"Report: {report_path}")
print(f"Bundle: {out / 'audit_bundle.json'}")
print(f"Issues: {len(issues)}")
PY

echo
echo "--- 3/4 Orchestrator health ---"
curl -fsS http://127.0.0.1:8888/health | python3 -c "import sys,json; d=json.load(sys.stdin); print('API:', d.get('status'), 'v'+d.get('version','?'))" || echo "WARN: HexStrike API not reachable on :8888"

echo
echo "--- 4/4 R1 (optional) ---"
python3 scripts/verify-r1-deepseek.py || echo "WARN: R1 not configured"

echo
echo "=== Demo complete ==="
ls -la "$REPORT_DIR"/audit-*-demo.md 2>/dev/null || true
