"""Generate SKILL.md and MCP tool stubs from workflow templates."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATED_SKILLS_DIR = _REPO_ROOT / ".cursor" / "skills" / "generated"
GENERATED_MCP_DIR = _REPO_ROOT / "src" / "hexstrike" / "workflow" / "generated_tools"


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", s.lower()).strip("_")


def render_skill_md(template: dict[str, Any]) -> str:
    wid = template.get("workflow_id") or template.get("skill_name", "unnamed_skill")
    params = template.get("parameters") or []
    steps = template.get("steps") or []

    if not params and template.get("input_schema"):
        in_schema = template["input_schema"]
        req = set(in_schema.get("required") or [])
        params = [
            {
                "name": k,
                "type": (v.get("type") if isinstance(v, dict) else "string"),
                "required": k in req,
                "description": (v.get("description") if isinstance(v, dict) else ""),
            }
            for k, v in (in_schema.get("properties") or {}).items()
        ]

    param_lines = "\n".join(
        f"- `{p['name']}` ({p.get('type', 'string')}){' *required*' if p.get('required', True) else ''}: {p.get('description', '')}"
        for p in params
    )

    step_lines_parts: list[str] = []
    for s in steps:
        tool = s.get("skill_id") or s.get("mcp_tool", "?")
        phase = s.get("phase", "")
        body = s.get("input_template") or s.get("inputs_from") or {}
        cond = s.get("next_step_condition") or ""
        step_lines_parts.append(
            f"{s.get('step_id', s.get('id', '?'))}. **{tool}** ({phase}) — {s.get('rationale', s.get('description', ''))}\n"
            f"   ```json\n{json.dumps(body, indent=2, ensure_ascii=False)}\n   ```"
            + (f"\n   Condition: {cond}" if cond else "")
        )
    step_lines = "\n".join(step_lines_parts)
    checklist = template.get("checklist") or []
    pitfalls = template.get("pitfalls") or []

    return f"""---
name: {wid}
description: Auto-generated from campaign trace {template.get('source_trace_id', 'unknown')}. Use for {template.get('name', wid)} workflows in HexStrike orchestrator. Invoke via MCP tool `{template.get('mcp_tool', {}).get('name', 'run_' + wid)}`.
---

# {template.get('name', wid)}

{template.get('description', 'Parameterized workflow generated by skill-builder.')}

**Version:** {template.get('version', '1.0.0')}  
**Tags:** {', '.join(template.get('tags') or [])}

## Parameters

{param_lines or '(none)'}

## Preconditions

{chr(10).join('- ' + p for p in template.get('preconditions') or []) or '- See authorization scope'}

## Steps

{step_lines}

## Postconditions

{chr(10).join('- ' + p for p in template.get('postconditions') or [])}

## Stop conditions

{chr(10).join('- ' + s for s in template.get('stop_conditions') or [])}

## Checklist

{chr(10).join('- [ ] ' + c for c in checklist)}

## Pitfalls

{chr(10).join('- ' + p for p in pitfalls)}
"""


def render_mcp_stub(template: dict[str, Any]) -> str:
    mcp = template.get("mcp_tool") or {}
    wid = template.get("workflow_id") or template.get("skill_name", "unnamed")
    tool_name = mcp.get("name") or f"run_{wid}"
    desc = mcp.get("description") or template.get("description") or tool_name
    params = template.get("parameters") or []
    param_sig = ", ".join(f"{p['name']}: str" for p in params if p.get("required", True))
    if not param_sig:
        param_sig = "target: str"

    steps_literal = json.dumps(template.get("steps") or [], indent=4)

    return f'''"""Auto-generated MCP tool stub — {tool_name}. Do not edit by hand; regenerate via skill-builder."""

from __future__ import annotations

from typing import Any

# Register with FastMCP in hexstrike_mcp.py:
# from hexstrike.workflow.generated_tools.{_slug(tool_name)} import {tool_name}


def {tool_name}({param_sig}) -> dict[str, Any]:
    """
    {desc}

    Executes workflow `{wid}` via orchestrator dispatch.
    """
    workflow_steps = {steps_literal}
    # TODO: wire to scatter_gather / hexstrike-orchestrator dispatch
    return {{
        "workflow_id": "{wid}",
        "status": "stub",
        "message": "Dispatch via orchestrator — implement runner hook",
        "steps": workflow_steps,
        "parameters": {{{", ".join(f'"{p["name"]}": {p["name"]}' for p in params if p.get("required", True)) or '"target": target'}}},
    }}
'''


def write_artifacts(
    template: dict[str, Any],
    *,
    skills_dir: Path | None = None,
    mcp_dir: Path | None = None,
    dry_run: bool = False,
) -> dict[str, str]:
    """Write SKILL.md and MCP stub; return paths written."""
    wid = _slug(template.get("workflow_id") or template.get("skill_name", "unnamed"))
    skills_root = skills_dir or GENERATED_SKILLS_DIR
    mcp_root = mcp_dir or GENERATED_MCP_DIR

    skill_path = skills_root / wid / "SKILL.md"
    mcp_name = (template.get("mcp_tool") or {}).get("name") or f"run_{wid}"
    mcp_path = mcp_root / f"{_slug(mcp_name)}.py"

    skill_content = render_skill_md(template)
    mcp_content = render_mcp_stub(template)

    written: dict[str, str] = {}
    if dry_run:
        written["skill_md"] = str(skill_path)
        written["mcp_stub"] = str(mcp_path)
        return written

    skill_path.parent.mkdir(parents=True, exist_ok=True)
    skill_path.write_text(skill_content, encoding="utf-8")
    written["skill_md"] = str(skill_path)

    if template.get("mcp_tool", {}).get("generate_stub", True):
        mcp_root.mkdir(parents=True, exist_ok=True)
        mcp_path.write_text(mcp_content, encoding="utf-8")
        written["mcp_stub"] = str(mcp_path)

    meta_path = skills_root / wid / "workflow-template.json"
    meta_path.write_text(json.dumps(template, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    written["workflow_template"] = str(meta_path)

    if template.get("input_schema"):
        skill_json = skills_root / wid / "skill.json"
        skill_payload = {
            "skill_name": template.get("workflow_id"),
            "description": template.get("description"),
            "tags": template.get("tags"),
            "input_schema": template.get("input_schema"),
            "output_schema": template.get("output_schema"),
            "steps": template.get("steps"),
            "source_attack_id": template.get("source_trace_id"),
        }
        skill_json.write_text(json.dumps(skill_payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        written["skill_json"] = str(skill_json)

    return written
